name: iOS Build

on:
  push:
    branches:
      - main

  release:
    types: [published]

jobs:
  ios-build:
    name: IOS Build
    runs-on: macOS-latest
    env:
      DEV_API_URL: ${{ secrets.DEV_API_URL }}
      STAG_API_URL: ${{ secrets.STAG_API_URL }}
      PROD_API_URL: ${{ secrets.PROD_API_URL }}
      IMG_BASE_URL: ${{ secrets.IMG_BASE_URL }}
      API_KEY: ${{ secrets.API_KEY }}
    defaults:
      run:
        working-directory: ios

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Restore buildcache
        uses: mikehardy/buildcache-action@v1
        continue-on-error: true

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true

      - name: Restore Pods cache
        uses: actions/cache@v3.0.8
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: pod install --repo-update

      - name: Build IOS App
        run: xcodebuild -workspace Mooviee.xcworkspace -scheme MoovieeDev build CODE_SIGNING_ALLOWED=NO
